EPS = 1e-8

CONFIG = 'default.yaml'

PATH_DATASET = 'datasets/'
PATH_STATE_DICT = 'state_dicts/'
PATH_RESULT = 'results/'
PATH_FIG = 'figs/'
PATH_TENSORBOARD = 'tensorboards/'

METR_LA = 'METR-LA'
PEMS_BAY = 'PEMS-BAY'
BJ_HIGHWAY = 'BJ-HIGHWAY'
BJ_SUBWAY = 'BJ-SUBWAY'
DATASETS = [METR_LA, PEMS_BAY, BJ_HIGHWAY, BJ_SUBWAY]
