---
data:
  task:
    flow:
      freq: 15
      history: 8
      horizon: 8
      horizons: [0, 1, 3, 7]
      metrics: [mae, rmse, wape]
    speed:
      freq: 5
      history: 12
      horizon: 12
      horizons: [2, 5, 11]
      metrics: [mae, rmse, mape]
  dataset:
    LA:
      task: speed
      num_nodes: 207
    BJ_highway:
      task: flow
      num_nodes: 264
    BJ_metro:
      task: flow
      num_nodes: 536
model:
  paradigm:
    s:
      batch_size: 64
      epoches: 100
      model_dim: 64
      node_dim: 32
      time_dim: 32
      weekday_dim: 16
    t:
      batch_size: 256
      epoches: 200
      model_dim: 128
      time_dim: 32
      weekday_dim: 16
    st:
      batch_size: 16
      epoches: 50
      model_dim: 64
      node_dim: 32
      time_dim: 32
      weekday_dim: 16
  model:
    STTransformer:
      paradigm: st
      encoder_layers: 2
      decoder_layers: 2
      heads: 4
      mask: True
    Transformer:
      paradigm: t
      encoder_layers: 2
      decoder_layers: 2
      heads: 4
    STransformer:
      paradigm: s
      num_layers: 3
      heads: 4
      mask: True
    RNN:
      paradigm: t
      rnn_type: GRU
      num_layers: 2
    RNNAttn:
      paradigm: t
      rnn_type: GRU
      num_layers: 2
      heads: 4
    DCRNN:
      paradigm: st
      num_layers: 2
      hops: 2
      inverse: True
