---
data:
  task:
    flow:
      start: 0
      end: 24
      freq: 15
      history: 8
      horizon: 4
      horizons: [0, 1, 3]
      metrics: [mae, rmse, wape]
    speed:
      start: 0
      end: 24
      freq: 5
      history: 12
      horizon: 12
      horizons: [2, 5, 11]
      metrics: [mae, rmse, mape]
  dataset:
    METR-LA:
      task: speed
      num_nodes: 207
      train_ratio: 0.7
      test_ratio: 0.2
    PEMS-BAY:
      task: speed
      num_nodes: 325
      train_ratio: 0.7
      test_ratio: 0.2
    BJ-HIGHWAY:
      task: flow
      num_nodes: 264
      train_ratio: 0.66
      test_ratio: 0.16
    BJ-SUBWAY:
      task: flow
      num_nodes: 536
      train_ratio: 0.66
      test_ratio: 0.16
model:
  paradigm:
    st:
      batch_size: 16
      epoches: 100
      patience: 10
    s:
      batch_size: 64
      epoches: 300
      patience: 30
    t:
      batch_size: 256
      epoches: 500
      patience: 50
  model:
    IsoMLP:
      paradigm: s
      model_dim: 32
    IsoRNN:
      paradigm: st
      framework: seq2seq
      rnn_attn: False
      model_dim: 32
      num_layers: 1
    STTransformer:
      paradigm: st
      model_dim: 16
      encoder_layers: 1
      decoder_layers: 1
      heads: 4
    Transformer:
      paradigm: t
      model_dim: 64
      encoder_layers: 1
      decoder_layers: 1
      heads: 4
    STransformer:
      paradigm: s
      model_dim: 64
      num_layers: 1
      heads: 4
    RNN:
      paradigm: t
      rnn_type: GRU
      model_dim: 64
      num_layers: 1
    RNNAttn:
      paradigm: t
      rnn_type: GRU
      model_dim: 64
      num_layers: 1
      heads: 4
    DCRNN:
      paradigm: st
      framework: seq2seq
      rnn_attn: False
      model_dim: 32
      num_layers: 1
      hops: 2
    GATRNN:
      paradigm: st
      framework: seq2seq
      rnn_attn: False
      model_dim: 32
      num_layers: 1
      heads: 4
